---
- hosts: all
  tasks:
    - name: Create Dev dir
      file:
        path: /home/ubuntu/Dev
        state: directory
      become_user: ubuntu


    - name: Checkout tmux conf
      git:
        repo: 'https://github.com/daghub/tmuxconf'
        dest: /home/ubuntu/Dev/tmuxconf
      become_user: ubuntu

    - name: install tmux
      apt:
        name: tmux
        state: present

    - name: create tmux symlink
      file:
        src: /home/ubuntu/Dev/tmuxconf/tmux.conf
        dest: /home/ubuntu/.tmux.conf
        state: link
      become_user: ubuntu

    - name: Ensure tmux session in .bashrc
      blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        marker: '# {mark} ANSIBLE MANAGED BLOCK - tmux'
        # insertbefore: BOF
        block: |
          if [[ -z "$TMUX" ]]; then
              ID=$(/usr/bin/tmux ls | grep -v1 attached | cut -d: -f1)
              if [[ -z "${ID}" ]]; then
                  /usr/bin/tmux new-session
              else
                  /usr/bin/tmux attach-session -t "${ID}"
              fi
          fi
      become_user: ubuntu

    - name: import kelleyk apt key
      apt_key:
        url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x873503a090750cdaeb0754d93ff0e01eeaafc9cd'
        state: present
      become: true

    - name: Add emacs apt repository
      apt_repository:
        repo: 'ppa:kelleyk/emacs'
        update_cache: yes
      become: true

    - name: Install emacs26
      apt:
        name: emacs26
        state: present
      become: true


